### PR TITLE
Add automated builds and windows build instructions

### PR DESCRIPTION
**Pull request by jsmolka**
Cause automated builds are great and building on Windows is much harder than expected...

Example output can be found [here](https://github.com/jsmolka/NanoboyAdvance/actions/runs/132538854).

If anything goes wrong in the future just @ me.

### CODE REVIEW

**Comment by fleroviux** [comment]
Nice! Thanks a lot @jsmolka ! This will be very useful.

**Comment by fleroviux** [comment]
@jsmolka Starting with the commit https://github.com/fleroviux/NanoboyAdvance/commit/5f4a2e217d4632e920eb1f24c9117cddf726bbcc the automated Windows build constantly fails. Do you know what might have went wrong? Seems like it can't find Clang anymore.

This is the error message:
> -- Building for: Visual Studio 16 2019
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:8 (project):
  No CMAKE_CXX_COMPILER could be found.
-- Configuring incomplete, errors occurred!
See also "D:/a/NanoboyAdvance/NanoboyAdvance/build/CMakeFiles/CMakeOutput.log".
See also "D:/a/NanoboyAdvance/NanoboyAdvance/build/CMakeFiles/CMakeError.log".
##[error]Process completed with exit code 1.

**Comment by jsmolka** [comment]
Weird, I just tried building on my machine and everything works fine. I'll take a look at it in the next few days.

**Comment by fleroviux** [comment]
Thanks!

**Comment by jsmolka** [comment]
I tried fixing it but not even the original version I pushed compiles at the moment (I tried it in my [fork](https://github.com/jsmolka/NanoboyAdvance/runs/823391145?check_suite_focus=true)). This has to be something on GitHubs end. I think there is an official actions repo so I will try my luck there^^.

**Comment by fleroviux** [comment]
Ah, that makes sense. I kind of suspected it wasn't actually caused by any change I made.

**Comment by fleroviux** [comment]
@jsmolka FYI cleaned the README up and moved the build guides to COMPILING.md. 
I've also reworked the build guides a bit and removed the part on how to install VCPKG and linked to the VCPKG Git for that instead.

**Pull request merged**
