### PR TITLE
Implement a high-level emulation of the MP2K audio mixer.

### PR DESCRIPTION
**Pull request by fleroviux**

### CODE REVIEW

**Comment by birdybro** [comment]
Hi!

I'm looking into what the specific reasoning was for this formula in the apu:

```cpp
sample[channel] += psg_sample * psg_volume * psg.master[channel] / (28.0 * 0x200);
```

Hopefully looking to help resolve this issue with the information --> https://github.com/MiSTer-devel/GBA_MiSTer/issues/143

Thank you so much! :)

**Comment by fleroviux** [comment]
@birdybro `psg_volume` can take values from 0 to 4 (see `psg_volume_tab`), `psg.master[channel]` can take values from 0 to 7. `psg_sample` iirc has a range of -0x1FC to 0x200 (because each channel has a range of -127 to +128). So dividing by `4 * 7 * 0x200` the mix of the channels is normalized to a roundabout -1.0f to +1.0f range. 

However this is for the HQ mixer, which uses floating point math for the final mix. See https://github.com/nba-emu/NanoBoyAdvance/blob/master/src/nba/src/hw/apu/apu.cpp#L186-L196 for the more accurate implementation which has the 28 factor but not the 0x200 factor.

**Comment by birdybro** [comment]
After talking with the developer of that core when I noticed something different...

https://github.com/nba-emu/NanoBoyAdvance/blob/a30da204a1c03e4adc981ac50b77327a002f0e50/src/nba/src/hw/apu/apu.cpp#L123

This bit order of the division factor is different than no$'s documentation (his would be represented as {4, 2, 1, 0} instead AFAICT). I am going to test making the MiSTer GBA core reflect your division factor since I suspect that's the root cause (and it's the easiest thing to test first lol).

**Comment by fleroviux** [comment]
@birdybro this is what I'm seeing in GBATEK (see SOUNDCNT_H):
```
  0-1   R/W  Sound # 1-4 Volume   (0=25%, 1=50%, 2=100%, 3=Prohibited)
```

**Comment by birdybro** [comment]
Yeah I was just being stupid and not reading it right. The core is correct. Sorry.

**Pull request merged**
